#!/usr/bin/sh

mount -t devtmpfs none /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys

echo "Waiting for /dev/mmcblk0p2..."
until  [ -b "/dev/mmcblk0p2" ]; do
  sleep 5
done

#rpi-otp-private-key -b > key.bin
KEY_PATH="test-key.bin"
#if cryptsetup open --type=luks2 --key-file "$KEY_PATH" /dev/mmcblk0p2 appfs; then
mkdir /media/mmcblk0p2
echo "Mounting /dev/mmcblkop2..."
mount /dev/mmcblk0p2

#mount /dev/mapper/appfs /media/mmcblk0p2
# else
#     mkdir /media/mmcblk0p2
#     mount /dev/mmcblk0p2 /media/mmcblk0p2
#     mkdir /root/mmcblk0p2
#     cp -r /media/mmcblk0p2/* /root/mmcblk0p2/
#     umount /media/mmcblk0p2
#     cryptsetup -q luksFormat --type=luks2 --key-file="$KEY_PATH" --pbkdf argon2id /dev/mmcblk0p2
#     cryptsetup open --type=luks2 --key-file "$KEY_PATH" /dev/mmcblk0p2 appfs
#     /usr/sbin/mke2fs -t ext4 /dev/mapper/appfs
#     mount /dev/mapper/appfs /media/mmcblk0p2
#     cp -r /root/mmcblk0p2/* /media/mmcblk0p2/
# fi

echo "Switching root :)"
exec switch_root /media/mmcblk0p2/ /sbin/init